[project]
name = "transaq"
version='1.0'
authors = [
  {name = "Ivan Kiselev", email = "yankoval@gmail.com"},
]

dependencies = [
  "requests",
  "pandas>1.2.2",
  "tapy",
  "coloredlogs",
  "argparse",
  "constants",
]
